locale: en

#In miliseconds
queue-speed: 2000
player-amount: 2
socket-host: localhost
socket-port: 1233
socket-password: "TOABSOLUTELYCHANGE"
use-same-queue: false
default-servers:
  - "lobby"
queued-servers:
  - "faction"
  - "invest"
permissions:
  join-queue-command: "advancedbungeequeue.command.join"
  pause-queue-command: "advancedbungeequeue.command.pause"
  unpause-queue-command: "advancedbungeequeue.command.unpause"
  on-queue-command: "advancedbungeequeue.command.on"
  off-queue-command: "advancedbungeequeue.command.off"
  bypass: "advancedbungeequeue.bypass"

# Permission: advancedbungeequeue.priority.high
priorities:
  High: 3
  Medium: 2
  Low: 1